export let timelineResourceData: Object[] = [
  {
    Id: 61,
    Location: "instagram",
    Subject: "Decoding",
    StartTime: new Date(2024, 7, 4, 9, 30),
    EndTime: new Date(2024, 7, 4, 10, 30),
    IsAllDay: false,
    EventType: "maintenance",
    CategoryColor: "#e3165b",
  },
  {
    Id: 62,
    Location: "facebook",
    Subject: "Bug Automation",
    StartTime: new Date(2024, 7, 6, 13, 30),
    EndTime: new Date(2024, 7, 6, 16, 30),
    IsAllDay: false,
    EventType: "maintenance",
  },
  {
    Id: 63,
    Location: "facebook",
    Subject: "Functionality testing",
    StartTime: new Date(2024, 7, 4, 9),
    EndTime: new Date(2024, 7, 4, 10, 30),
    IsAllDay: false,
    CategoryColor: "#357cd2",
    EventType: "maintenance",
  },
  {
    Id: 64,
    Location: "instagram",
    Subject: "Resolution-based testing",
    StartTime: new Date(2024, 7, 7, 12, 0, 0, 0),
    EndTime: new Date(2024, 7, 7, 13),
    IsAllDay: false,
    EventType: "maintenance",
    CategoryColor: "#e3165b",
  },
  {
    Id: 65,
    Location: "tiktok",
    Subject: "Test report Validation",
    StartTime: new Date(2024, 7, 4, 15),
    EndTime: new Date(2024, 7, 4, 18),
    IsAllDay: false,
    EventType: "maintenance",
    CategoryColor: "#000000",
  },
  {
    Id: 66,
    Location: "facebook",
    Subject: "Test case correction",
    StartTime: new Date(2024, 7, 12, 14),
    EndTime: new Date(2024, 7, 12, 16),
    IsAllDay: false,
    EventType: "maintenance",
  },
  {
    Id: 67,
    Location: "facebook",
    Subject: "Bug fixing",
    StartTime: new Date(2024, 7, 28, 14, 30),
    EndTime: new Date(2024, 7, 28, 18, 30),
    IsAllDay: true,
    status: "Completed",
    Priority: "High",
    EventType: "maintenance",
  },
  {
    Id: 68,
    Location: "facebook",
    Subject: "Run test cases",
    StartTime: new Date(2024, 7, 4, 17, 30),
    EndTime: new Date(2024, 7, 4, 19, 30),
    IsAllDay: false,
    EventType: "maintenance",
  },
  {
    Id: 70,
    Location: "tiktok",

    Subject: "Bug Automation",
    StartTime: new Date(2024, 7, 20, 18, 30),
    EndTime: new Date(2024, 7, 20, 20, 30),
    IsAllDay: false,
    EventType: "maintenance",
  },
];
